services:
  mpeg-dash-processor-1:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-1
    ports:
      - "8100:8080"  # HTTP  - Container 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  mpeg-dash-processor-2:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-2
    ports:
      - "8200:8080"  # HTTP  - Container 2
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  mpeg-dash-processor-3:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-3
    ports:
      - "8300:8080"  # HTTP  - Container 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  mpeg-dash-processor-4:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-4
    ports:
      - "8400:8080"  # HTTP  - Container 4
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  mpeg-dash-processor-5:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-5
    ports:
      - "8500:8080"  # HTTP  - Container 5
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  mpeg-dash-processor-6:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-6
    ports:
      - "8600:8080"  # HTTP  - Container 6
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  mpeg-dash-processor-7:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-7
    ports:
      - "8700:8080"  # HTTP  - Container 7
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  mpeg-dash-processor-8:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-8
    ports:
      - "8800:8080"  # HTTP  - Container 8
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped

  load-balancer:
    build: ./load-balancer
    container_name: load-balancer
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped

networks:
  default:
    name: mpeg-dash-network
    driver: bridge
