services:
  mpeg-dash-processor-1:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-1
    ports:
      - "8100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - /var/lib/data/server-1:/app/wwwroot/Static

  mpeg-dash-processor-2:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-2
    ports:
      - "8200:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=true
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - /var/lib/data/server-2:/app/wwwroot/Static

  mpeg-dash-processor-3:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-3
    ports:
      - "8300:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - /var/lib/data/server-3:/app/wwwroot/Static

  mpeg-dash-processor-4:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-4
    ports:
      - "8400:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - /var/lib/data/server-4:/app/wwwroot/Static

  mpeg-dash-processor-5:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-5
    ports:
      - "8500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - /var/lib/data/server-5:/app/wwwroot/Static

  mpeg-dash-processor-6:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-6
    ports:
      - "8600:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - /var/lib/data/server-6:/app/wwwroot/Static

  mpeg-dash-processor-7:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-7
    ports:
      - "8700:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 128M
    volumes:
      - /var/lib/data/server-7:/app/wwwroot/Static

  mpeg-dash-processor-8:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-8
    ports:
      - "8800:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 6M
    volumes:
      - /var/lib/data/server-8:/app/wwwroot/Static

  load-balancer:
    build: ./load-balancer
    container_name: load-balancer
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: 8192M
        reservations:
          cpus: "1.0"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        compress: "true"

  monitoring-dashboard:
    image: nginx:alpine
    container_name: monitoring-dashboard
    ports:
      - "3001:80"
    volumes:
      - ./monitoring/dashboard.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped

  metrics-collector:
    image: python:3.11-alpine
    container_name: metrics-collector
    ports:
      - "3002:3002"
    volumes:
      - ./monitoring:/app/monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache docker-cli &&
        pip install --no-cache-dir -r /app/monitoring/requirements.txt &&
        python3 /app/monitoring/metrics-api.py
      "
    restart: unless-stopped

networks:
  default:
    name: mpeg-dash-network
    driver: bridge
