services:
  mpeg-dash-processor-1:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-1
    ports:
      - "8100:8080"  # HTTP  - Container 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 64MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 128M       # Reserve 8MB RAM

  mpeg-dash-processor-2:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-2
    ports:
      - "8200:8080"  # HTTP  - Container 2
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=true  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 64MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 128M       # Reserve 8MB RAM

  mpeg-dash-processor-3:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-3
    ports:
      - "8300:8080"  # HTTP  - Container 3
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 64MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 128M       # Reserve 8MB RAM

  mpeg-dash-processor-4:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-4
    ports:
      - "8400:8080"  # HTTP  - Container 4
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 64MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 128M       # Reserve 8MB RAM

  mpeg-dash-processor-5:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-5
    ports:
      - "8500:8080"  # HTTP  - Container 5
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 512MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 128M       # Reserve 8MB RAM

  mpeg-dash-processor-6:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-6
    ports:
      - "8600:8080"  # HTTP  - Container 6
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 64MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 128M       # Reserve 8MB RAM

  mpeg-dash-processor-7:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-7
    ports:
      - "8700:8080"  # HTTP  - Container 7
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 64MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 128M       # Reserve 8MB RAM

  mpeg-dash-processor-8:
    build: ./mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-8
    ports:
      - "8800:8080"  # HTTP  - Container 8
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false  # Set to true to force disk I/O on every request
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"        # Limit to 1 CPU core
          memory: 1024M       # Limit to 64MB RAM
        reservations:
          cpus: "0.25"       # Reserve 0.25 CPU cores
          memory: 6M       # Reserve 8MB RAM

  load-balancer:
    build: ./load-balancer
    container_name: load-balancer
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    # ulimits:
    #   nofile:
    #     soft: 200000
    #     hard: 200000
    # sysctls:
    #   net.core.somaxconn: 65535
    #   net.ipv4.tcp_max_syn_backlog: 262144
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "1.0"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"        # Maximum size per log file
        max-file: "3"           # Keep 3 log files (300MB total)
        compress: "true"        # Compress rotated logs

  # Monitoring dashboard (web interface)
  monitoring-dashboard:
    image: nginx:alpine
    container_name: monitoring-dashboard
    ports:
      - "3001:80"
    volumes:
      - ./monitoring/dashboard.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped

  # Metrics collection service
  metrics-collector:
    image: python:3.11-alpine
    container_name: metrics-collector
    ports:
      - "3002:3002"
    volumes:
      - ./monitoring:/app/monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache docker-cli &&
        pip install --no-cache-dir -r /app/monitoring/requirements.txt &&
        python3 /app/monitoring/metrics-api.py
      "
    restart: unless-stopped

networks:
  default:
    name: mpeg-dash-network
    driver: bridge
