services:
  nanomq:
    image: emqx/nanomq:latest
    container_name: nanomq-broker
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8081:8081"
    volumes:
      - ./core/publish-subscribe/nanomq.conf:/etc/nanomq.conf:ro
      - nanomq-data:/opt/nanomq/data
    restart: unless-stopped
    command: ["nanomq", "start", "--conf", "/etc/nanomq.conf"]
    
  mpeg-dash-processor-1:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-1
    ports:
      - "8100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-1:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=12
      - READ_DISK_LIMIT_MBPS=512
      - MEMORY_LIMIT_MB=4096
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '512mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 4096M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-1:/app/wwwroot/Static

  mpeg-dash-processor-2:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-2
    ports:
      - "8200:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=true
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-2:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=10
      - READ_DISK_LIMIT_MBPS=256
      - MEMORY_LIMIT_MB=2048
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '256mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-2:/app/wwwroot/Static

  mpeg-dash-processor-3:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-3
    ports:
      - "8300:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-3:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=8
      - READ_DISK_LIMIT_MBPS=128
      - MEMORY_LIMIT_MB=1024
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '128mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-3:/app/wwwroot/Static

  mpeg-dash-processor-4:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-4
    ports:
      - "8400:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-4:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=6
      - READ_DISK_LIMIT_MBPS=64
      - MEMORY_LIMIT_MB=512
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '64mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-4:/app/wwwroot/Static

  mpeg-dash-processor-5:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-5
    ports:
      - "8500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-5:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=4
      - READ_DISK_LIMIT_MBPS=32
      - MEMORY_LIMIT_MB=512
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '32mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-5:/app/wwwroot/Static

  mpeg-dash-processor-6:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-6
    ports:
      - "8600:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-6:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=3
      - READ_DISK_LIMIT_MBPS=16
      - MEMORY_LIMIT_MB=512
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '16mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-6:/app/wwwroot/Static

  mpeg-dash-processor-7:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-7
    ports:
      - "8700:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-7:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=2
      - READ_DISK_LIMIT_MBPS=8
      - MEMORY_LIMIT_MB=512
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '8mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-7:/app/wwwroot/Static

  mpeg-dash-processor-8:
    build: ./core/mpeg-dash-processor/Application
    container_name: mpeg-dash-processor-8
    ports:
      - "8800:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DISABLE_FILE_CACHING=false
      - MQTT_BROKER_URL=mqtt://nanomq-broker:1883
      - SERVER_SOCKET=mpeg-dash-processor-8:8080
      - METRICS_PUBLISH_INTERVAL_SECONDS=1
      - READ_DISK_LIMIT_MBPS=4
      - MEMORY_LIMIT_MB=512
    restart: unless-stopped
    blkio_config:
      device_read_bps:
        - path: /dev/sdd
          rate: '4mb'
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 64M
    volumes:
      - /var/lib/data/server-8:/app/wwwroot/Static

  load-balancer:
    build: ./core/load-balancer
    container_name: load-balancer
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: 8192M
        reservations:
          cpus: "1.0"
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        compress: "true"

  monitoring-dashboard:
    image: nginx:alpine
    container_name: monitoring-dashboard
    ports:
      - "3001:80"
    volumes:
      - ./monitoring/dashboard.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped

  metrics-collector:
    image: python:3.11-alpine
    container_name: metrics-collector
    ports:
      - "3002:3002"
    volumes:
      - ./monitoring:/app/monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache docker-cli &&
        pip install --no-cache-dir -r /app/monitoring/requirements.txt &&
        python3 /app/monitoring/metrics-api.py
      "
    restart: unless-stopped

volumes:
  nanomq-data:

networks:
  default:
    name: mpeg-dash-network
    driver: bridge
